### ISSUE TITLE
ES2015 features break IE11

### ISSUE THREAD

**Issue by petermikitsh** [vercel/title#28]
In https://github.com/zeit/title/blob/master/lib/index.js#L26, a default parameter is used:

```
  str = str.toLowerCase().replace(regex, (m, lead = '', forced, lower, rest) => {
                                                  ^^^^
```

A couple other ES2015 features, such as the spread syntax, are used as well.

These choices break in IE11. Including an ES5 build, or refactoring the code to avoid ES2015, would fix the issue.

**Comment by leerob** [comment]
Closing as won't fix for IE11 support 🙏 Thank you regardless!
