### ISSUE TITLE
per-Part should be Per-part

### ISSUE THREAD

**Issue by Hongbo-Miao** [vercel/title#29]
Currently the tool gives this title:

```
Healthcare Systems Manufacturer Reduces per-Part Cost 10x by Harnessing New Open Additive Ecosystem
```

However, I think it should be

```
Healthcare Systems Manufacturer Reduces Per-part Cost 10x by Harnessing New Open Additive Ecosystem
```

based on https://alcts.ala.org/ccdablog/?tag=chicago-manual-of-style.

Please correct me if I am wrong. Thanks

By the way, a very useful tool!

**Comment by leerob** [comment]
Thanks for reporting. If you would like to contribute back, I'm happy to review your PR. Otherwise, closing this as won't fix 🙏
