### ISSUE TITLE
'ñ' causes a capitalization bug

### ISSUE THREAD

**Issue by macadev** [vercel/title#33]
Hi,

I noticed this while using this module today:

`
title('diseño') // 'DiseñO'
`

Using 'ñ' results in the next letter being capitalized. I haven't dug to figure out what's causing this, but I just wanted to surface the problem. Thanks for all the hard work.

**Comment by j-f1** [comment]
Same for “FernáNdez.”

**Comment by SeriousBug** [comment]
Hi, are there any ongoing work to fix this issue? Otherwise, would you accept a PR to fix this?

**Comment by leerob** [comment]
Fixed with https://github.com/vercel/title/pull/62 - thank you!
