### ISSUE TITLE
Last word of title should always be capitalized

### ISSUE THREAD

**Issue by tywmick** [vercel/title#40]
I don't have direct access to the relevant [Chicago Manual of Style section](https://www.chicagomanualofstyle.org/book/ed17/part2/ch08/psec157.html), but indirectly, everywhere I look online from [Grammar Girl](https://www.quickanddirtytips.com/education/grammar/capitalizing-titles) to [Capitalize My Title](https://capitalizemytitle.com/#ChicagoStyle) tells me that the last word of the title should always be capitalized regardless of whether or not it's a conjunction, article, or preposition.

This tool currently does not capitalize the last word of the title if it is one of the words in `lower-case.js`. For example,

```zsh
title "what on earth is going on"
# What on Earth Is Going on [copied]
```

It should return <code>What on Earth Is Going <strong>On</strong></code>.

**Comment by leerob** [comment]
Merged! https://github.com/vercel/title/pull/58
