### ISSUE TITLE
Incorrect result for Vietnamese

### ISSUE THREAD

**Issue by meikidd** [vercel/title#63]
Hi, thanks for making this package. I found the result for Vietnamese is incorrect, please see examples below.

```
console.log(title("đội")); // output "độI", but expect "Đội"
console.log(title("tuyển")); // output "TuyểN", but expect "Tuyển"
```

**Comment by dferber90** [comment]
Seems like a duplicate of https://github.com/vercel/title/issues/33 which has https://github.com/vercel/title/pull/62 open. I haven't verified whether #62 fixes this case as well though.

**Comment by SeriousBug** [comment]
Looks like #62 does fix this, I added the examples into the test cases in the PR.

**Comment by meikidd** [comment]
Thanks a lot, looking forward a new version for this.

**Comment by leerob** [comment]
Fixed with https://github.com/vercel/title/pull/62 - thank you!
