### ISSUE TITLE
Issue with 3.5.0 C++ Regular Expression

### ISSUE THREAD

**Issue by hkievet** [vercel/title#74]
Getting an issue with the `title()` function  `Invalid regular expression: /\bC++\b/: Nothing to repeat`.  Probably related to the symbols.js update 88794450a9773ba7dff6795d63474f1ab5fff9d3

**Comment by hkievet** [comment]
Fixed 280a945831441f50f71e8c9f41a50951b9066c22

**Comment by leerob** [comment]
Thank you so much for reporting!
