### ISSUE TITLE
Update all dependencies to latest

### ISSUE THREAD

**Issue by Moe23333** [vercel/title#79]
I noticed that its dependencies are too old, so you have better update them, and it's recommended to use @^x.x.x or @>=x.x.x to assign versions instead of an exact version code.

It's important to keep the dependencies fresh, and if not, it may cause security problems.

**Comment by leerob** [comment]
Open to contributions!

**Comment by leerob** [comment]
Closing as duplicate of https://github.com/vercel/title/issues/69.
